### Create a category
POST {{host}}/api/v1/categories
Content-Type: application/json

{
  "name": "Software development"
}

> {%
    client.global.set("sofwareCategoryId", response.body.id)
%}

### Get all categories
GET {{host}}/api/v1/categories


### Create topic for category
POST {{host}}/api/v1/categories/{{sofwareCategoryId}}/topics
Content-Type: application/json

{
  "name": "Java 19 released",
  "userId": "2e0c8f82-88d3-20cf-2112-a0678be9c201",
  "tags": ["NSFW"]
}

> {%
 client.test("Response status should be 200", function () {
     client.assert(response.status === 200, "Expected 200 but got: " + response.status)
 })
 %}

### Get topics of a category
GET {{host}}/api/v1/categories/{{sofwareCategoryId}}/topics
Content-Type: application/json

> {%
 client.global.set("topicId", response.body[0].id)
 %}

### Get a particular topic
GET {{host}}/api/v1/categories/{{sofwareCategoryId}}/topics/{{topicId}}
Content-Type: application/json

###
POST {{host}}/api/v1/categories/{{sofwareCategoryId}}/topics/b0574534-c156-4cd7-8cca-18e531d85aba/tags
Content-Type: application/json

[
  "NSFW", "TRIGGER_WARNING"
]

### Create random category
POST http://localhost:8081/api/v1/categories
Content-Type: application/json

{
  "name": "{{$random.alphabetic(20)}}"
}

### Delete a topic
DELETE {{host}}/api/v1/categories/{{sofwareCategoryId}}/topics/{{topicId}}
Content-Type: application/json

### Get comments for a topic
GET {{host}}/api/v1/categories/{{sofwareCategoryId}}/topics/{{topicId}}/comments
Content-Type: application/json

### Create a comment for a topic
POST {{host}}/api/v1/categories/{{sofwareCategoryId}}/topics/{{topicId}}/comments
Content-Type: application/json

{
  "userId": "2e0c8f82-88d3-20cf-2112-a0678be9c201",
  "text": "Yay"
}

> {%
 client.global.set("commentId", response.body.commentId)
 %}

### Get comment by id
GET {{host}}/api/v1/categories/{{sofwareCategoryId}}/topics/{{topicId}}/comments/{{commentId}}
Content-Type: application/json

### Like comment
POST {{host}}/api/v1/categories/{{sofwareCategoryId}}/topics/{{topicId}}/comments/{{commentId}}/likes
Content-Type: application/json

### Delete a comment
DELETE {{host}}/api/v1/categories/{{sofwareCategoryId}}/topics/{{topicId}}/comments/{{commentId}}
Content-Type: application/json

###
