### Create a category
POST {{host}}/api/v1/categories
Content-Type: application/json

{
  "name": "Software development"
}

> {%
    client.global.set("sofwareCategoryId", response.body.id)
%}

### Get all categories
GET {{host}}/api/v1/categories

### Get category by id
GET {{host}}/api/v1/categories/{{sofwareCategoryId}}
Content-Type: application/json

### Create topic for category
POST {{host}}/api/v1/categories/{{sofwareCategoryId}}/topics
Content-Type: application/json

{
  "name": "DynamoDB is fun",
  "userName": "john",
  "tags": ["NSFW"]
}

> {%
 client.test("Response status should be 200", function () {
     client.assert(response.status === 200, "Expected 200 but got: " + response.status)
 })
 %}

### Get topics of a category
GET {{host}}/api/v1/categories/{{sofwareCategoryId}}/topics
Content-Type: application/json

> {%
 client.global.set("topicId", response.body[0].id)
 %}

### Get a particular topic
GET {{host}}/api/v1/categories/{{sofwareCategoryId}}/topics/{{topicId}}
Content-Type: application/json

### Add tags for a topic
POST {{host}}/api/v1/categories/{{sofwareCategoryId}}/topics/{{topicId}}/tags
Content-Type: application/json

[
  "NSFW", "TRIGGER_WARNING"
]

### Create random category
POST http://localhost:8081/api/v1/categories
Content-Type: application/json

{
  "name": "{{$random.alphabetic(20)}}"
}

### Delete a topic
DELETE {{host}}/api/v1/categories/{{sofwareCategoryId}}/topics/{{topicId}}
Content-Type: application/json

### Get comments for a topic
GET {{host}}/api/v1/categories/{{sofwareCategoryId}}/topics/{{topicId}}/comments
Content-Type: application/json

### Create a comment for a topic
POST {{host}}/api/v1/categories/{{sofwareCategoryId}}/topics/{{topicId}}/comments
Content-Type: application/json

{
  "userName": "john",
  "text": "Finally"
}

> {%
 client.global.set("commentId", response.body.commentId)
 %}

### Get comment by id
GET {{host}}/api/v1/categories/{{sofwareCategoryId}}/topics/{{topicId}}/comments/{{commentId}}
Content-Type: application/json

### Like comment
POST {{host}}/api/v1/categories/{{sofwareCategoryId}}/topics/{{topicId}}/comments/{{commentId}}/likes
Content-Type: application/json

### Delete a comment
DELETE {{host}}/api/v1/categories/{{sofwareCategoryId}}/topics/{{topicId}}/comments/{{commentId}}
Content-Type: application/json

###
### Get topics created by user
GET {{host}}/api/v1/users/john/topics
###
